name: salmon-sleuth
channels:
    - conda-forge
    - bioconda
    - r
    - defaults
dependencies:
    - python=3.6
    - pandas 

    - salmon
    - r-wasabi
    - r-sleuth
    - r-dplyr

    - pip
    - pip:
        - snakemake==5.8.2
